name: SHRP CI
on:
  workflow_dispatch:
jobs:
  build:
    name: SHRP Build CI
    runs-on: ubuntu-20.04
    env:
      OEM: samsung
      DEVICE: jflte
      BRANCH: shrp-9.0
    steps:
      - name: Cleanup
        uses: rokibhasansagar/slimhub_actions@main
      - name: Installing build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install gperf gcc-multilib gcc-10-multilib g++-multilib g++-10-multilib libc6-dev lib32ncurses5-dev x11proto-core-dev libx11-dev tree lib32z-dev libgl1-mesa-dev libxml2-utils xsltproc bc ccache lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libwxgtk3.0-gtk3-dev libxml2 lzop pngcrush schedtool squashfs-tools imagemagick libbz2-dev lzma ncftp qemu-user-static libstdc++-10-dev libncurses5 python axel
      - name: Install OpenJDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'
      - name: Syncing SHRP sources
        run: |
          mkdir ~/SHRP
          cd ~/SHRP
          mkdir ~/.bin
          curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > ~/.bin/repo
          python3 ~/.bin/repo init --depth=1 -u https://github.com/SHRP/manifest.git -b v3_9.0
          python3 ~/.bin/repo sync -c --force-sync --optimized-fetch --no-tags --no-clone-bundle --prune -j$(nproc --all)
          git clone --depth=1 --branch ${{ env.BRANCH }} --single-branch https://github.com/unlegacy-devices/twrp_device_${{ env.OEM }}_${{ env.DEVICE }}.git device/${{ env.OEM }}/${{ env.DEVICE }}
          git clone --depth=1 --branch twrp-jf --single-branch https://github.com/JDCTeam/android_kernel_samsung_jf.git kernel/samsung/jf
      - name: Building SHRP
        run: |
          OLDPATH=$PATH
           OLDJAVAHOME=$JAVA_HOME
          export PATH="$HOME/.jdk_7/java-se-7u75-ri/bin:$PATH"
          export JAVA_HOME="$HOME/.jdk_7/java-se-7u75-ri"
          cd ~/SHRP
          source build/envsetup.sh
          export ALLOW_MISSING_DEPENDENCIES=true
          export LC_ALL="C"
          lunch omni_${{ env.DEVICE }}-eng
          make -j$(nproc --all) recoveryimage
          export PATH=$OLDPATH
          export JAVA_HOME=$OLDJAVAHOME
      - name: Uploading SHRP builds
        uses: actions/upload-artifact@v2
        with:
          name: shr≈ë
          path: /home/runner/SHRP/out/target/product/${{ env.DEVICE }}/recovery.*
